spring:
  data:
    mongo:
#      uri: mongodb+srv://root:root@springboot.xyuvw.mongodb.net/?retryWrites=true&w=majority&appName=SpringBoot
      database: journaldb
#      auto-index-creation: true
#server:
#  port: 8082
#server:
#  port: 8081
#  servlet:
#    context-path: /abc